global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']

  - job_name: 'selos-service'
    static_configs:
      - targets: ['selos-service:3004']

  - job_name: 'verificacao-service'
    static_configs:
      - targets: ['verificacao-service:3005']

  - job_name: 'reputacao-service'
    static_configs:
      - targets: ['reputacao-service:3006']

  - job_name: 'seguranca-vibracional-service'
    static_configs:
      - targets: ['seguranca-vibracional-service:3007']

  - job_name: 'economia-service'
    static_configs:
      - targets: ['economia-service:3008']

  - job_name: 'antifraude-service'
    static_configs:
      - targets: ['antifraude-service:3009']
